# Generated by Django 4.0.5 on 2022-06-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='people',
        ),
    ]
