# Generated by Django 4.0.5 on 2022-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dinein',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
